### Employee
GET http://localhost:3001/account
### collector
GET http://localhost:3001/collector
### janitor
GET http://localhost:3001/janitor
### Depots
GET http://localhost:3001/overviewDepot
### Vehicles
GET http://localhost:3001/vehicles
### MCPs
GET http://localhost:3001/overviewMCP
### GTCs
GET http://localhost:3001/overviewGTC
### routedata
GET http://localhost:3001/routedata
### Delete route
DELETE http://localhost:3001/routedata/del/Route1

### Add route (routing)
POST http://localhost:3001/routedata/add
Content-Type: application/json

{
    "name": "HCMUT Company",
    "from": "Depot3",
    "to": {
        "id": 3,
        "name": "SAD"
    },
    "mcps": [1,3,4,5],
    "status": "1"
}

#### Assign route
PUT http://localhost:3001/collector/assign/3/2

#### Assign mcp
PUT http://localhost:3001/janitor/assign/3/2